
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo Image repo name $IMAGE_REPO_NAME
      - echo Image tag $IMAGE_TAG
      - echo Repository URI $REPOSITORY_URI
  build:
    commands:
      - echo Starting build...
      - printf "source_version = '%s'" $CODEBUILD_RESOLVED_SOURCE_VERSION > lti_inspector/build_info.py
      - printf "build_timestamp = '%s'" $(date "+%Y-%m-%d %H:%M:%S") >> lti_inspector/build_info.py
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build complete.
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"lti-inspector-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
